# Generated by Django 2.1.7 on 2019-03-06 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_papayaimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='papayaimage',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='papayaimage',
            name='url',
        ),
    ]
