# Generated by Django 2.1.7 on 2019-03-06 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20190306_2222'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PapayaImage',
        ),
    ]
