# Generated by Django 2.1.7 on 2019-03-13 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_room_tenant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='house_tenant',
        ),
        migrations.AlterField(
            model_name='room',
            name='house_room',
            field=models.ForeignKey(default='0000000', editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='room', to='main_app.House'),
        ),
        migrations.DeleteModel(
            name='tenant',
        ),
    ]
