# Generated by Django 2.1.7 on 2019-03-13 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20190313_0128'),
    ]

    operations = [
        migrations.CreateModel(
            name='tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=40, unique=True)),
                ('phone', models.IntegerField()),
                ('age', models.IntegerField()),
                ('job', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('house_tenant', models.ForeignKey(default='0000000', on_delete=django.db.models.deletion.DO_NOTHING, related_name='tenant_house', to='main_app.House')),
            ],
        ),
        migrations.AlterField(
            model_name='room',
            name='house_room',
            field=models.ForeignKey(default='0000000', on_delete=django.db.models.deletion.CASCADE, related_name='room', to='main_app.House'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='room_tenant',
            field=models.ForeignKey(default='0000000', on_delete=django.db.models.deletion.DO_NOTHING, related_name='tenant_room', to='main_app.Room'),
        ),
    ]
